DROP TABLE assay CASCADE CONSTRAINTS ;

DROP TABLE spectrum_cluster CASCADE CONSTRAINTS ;

DROP TABLE cluster_has_psm CASCADE CONSTRAINTS ;

DROP TABLE cluster_has_spectrum CASCADE CONSTRAINTS ;

DROP TABLE cluster_run CASCADE CONSTRAINTS ;

DROP TABLE cluster_statistics CASCADE CONSTRAINTS ;

DROP TABLE psm CASCADE CONSTRAINTS ;

DROP TABLE spectrum CASCADE CONSTRAINTS ;

DROP SEQUENCE assay_pk_sequence ;

DROP SEQUENCE cluster_pk_sequence ;

DROP SEQUENCE psm_pk_sequence ;

DROP SEQUENCE spectrum_pk_sequence ;